services:
  app_v2:
    image: jrmakercrmv2/jr_maker_crm_v2:latest  # Cambiado a la etiqueta 'latest'
    container_name: jr_maker_crm_v2
    ports:
      - "8002:8002"
    volumes:
      - /home/jr-crm-storage-no-borrar-v2:/app/storage/app/public
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      
      # Wompi keys
      WOMPI_PUBLIC_KEY: ${WOMPI_PUBLIC_KEY}
      WOMPI_PRIVATE_KEY: ${WOMPI_PRIVATE_KEY}
      WOMPI_INTEGRITY_SECRET: ${WOMPI_INTEGRITY_SECRET}
      WOMPI_ENV: ${WOMPI_ENV}
      
      # CLOUDFLARE CAPTCHA KEYS
      TURNSTILE_SITE_KEY: ${TURNSTILE_SITE_KEY}
      TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY}
      
      # Logging
      LOG_CHANNEL: ${LOG_CHANNEL}
      LOG_DEPRECATIONS_CHANNEL: ${LOG_DEPRECATIONS_CHANNEL}
      LOG_LEVEL: ${LOG_LEVEL}
      
      # Database config (nueva base de datos para evitar conflictos)
      DB_CONNECTION: mysql
      DB_HOST: mysql_shared
      DB_PORT: 3306
      DB_DATABASE: jr_maker_sas_v2  
      DB_USERNAME: root
      DB_PASSWORD: ae031323
      
      # Redis config
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      
      # Mail config
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8002
    networks:
      - nginxpm

  worker_v2:
    image: jrmakercrmv2/jr_maker_crm_v2:latest  # Cambiado a la etiqueta 'latest'
    container_name: jr_maker_crm_worker_v2
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      
      # Database config (misma configuración de la nueva base de datos)
      DB_CONNECTION: mysql
      DB_HOST: mysql_shared
      DB_PORT: 3306
      DB_DATABASE: jr_maker_sas_v2  
      DB_USERNAME: root
      DB_PASSWORD: ae031323
      
      # Redis config
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    command: php artisan queue:work --daemon --sleep=3 --tries=3 --timeout=90
    restart: unless-stopped
    networks:
      - nginxpm

networks:
  nginxpm:
    external: true
